#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightmotor,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait(1);
	startMotor(leftmotor, 127);
	startMotor(rightmotor, 127);
	wait(1);
	startMotor(leftmotor, -127);
	startMotor(rightmotor, -127);
	wait(1);
	stopMotor(leftmotor);
	stopMotor(rightmotor);
	while (true) {
		if(vexRT[Ch3]*vexRT[Ch2] <= 0){ //Opposite directions or only one on
			motor[leftmotor] = -vexRT[Ch3]*0.6;
			motor[rightmotor] = vexRT[Ch2]*0.6;
		}
		else{//Same direction
			motor[leftmotor] = -vexRT[Ch3];
		  motor[rightmotor] = vexRT[Ch2];
		}
	}

}
